version: '3.8'

services:
  eventstore:
    image: eventstore/eventstore:20.10.2-buster-slim
    container_name: eventstoredb
    hostname: eventstoredb
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
    networks:
      sample-network:
    restart: unless-stopped
  #---------------------------------------------------------------------------------------------------------------------
#  postgres:
#    image: postgres
#    container_name: postgres
#    hostname: postgres
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER:-postgres}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
#      PGDATA: /data/postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - type: volume
#        source: postgres-volume-data
#        target: /data/postgres
#    networks:
#      sample-network:
#    restart: unless-stopped

networks:
  sample-network:
    name: event-sourcing-cqrs-eventstoredb-sample.local
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 171.28.0.0/16
volumes:
  eventstore-volume-data:
    name: eventstore-volume-data
  eventstore-volume-logs:
    name: eventstore-volume-logs
  postgres-volume-data:
    name: postgres-volume-data
